<div class="container">       
      <div class="panel panel-primary">
      <div class="panel-heading"><h3>Historial de Entradas y Salidas</h3></div>
      <div class="panel-body">
        <table class="table table-striped">
          <tr>
            <th>Nombre</th>
            <th>Documento</th>
            <th>Entró</th>
            <th>Salió</th>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
        </table>
      </div>
    </div>
</div>