<div class="container">       
      <div class="panel panel-primary">
      <div class="panel-heading"><h3>Registros</h3></div>
      <div class="panel-body">
        <table class="table table-striped">
          <tr>
            <th>Nombre</th>
            <th>Documento</th>
            <th>Correo</th>
            <th>Telefono</th>
            <th>P. Formación</th>
            <th>Vehiculo</th>
            <th>Contraseña</th>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
          <tr>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
            <td>******</td>
          </tr>
        </table>
      </div>
    </div>
</div>